### ISSUE TITLE
Date label clipping into clock when disabling brackets 

### ISSUE THREAD

**Issue by hiergiltdiestfu** [bluecaret/carettab#105]
In the v3 beta, when disabling the brackets on the clock, the date string immediately jumped up into the clock string. This is not fixed by e.g. closing the config pane, or opening a new tab without the config pane open.
![image](https://user-images.githubusercontent.com/10924590/50868053-fe67db80-13ad-11e9-885d-a7955725ae3b.png)
![image](https://user-images.githubusercontent.com/10924590/50868077-1b9caa00-13ae-11e9-9244-a7ae2deee35d.png)

Chrome Version 71.0.3578.98

**Comment by hiergiltdiestfu** [comment]
Possibly related, when adding the week number to the date, the whole date area jumps up into the clock area.

![image](https://user-images.githubusercontent.com/10924590/50868279-070ce180-13af-11e9-928e-b68d56c22835.png)

**Comment by hiergiltdiestfu** [comment]
Looks like adding or removing elements that affect vertical layout should trigger an automatic reset of the Offsets of the display areas

**Comment by bluecaret** [comment]
First thank you for all the feedback today!

This is something I was worried about... I wanted full customization with offsets and everything, but yes that does mean when adjusting/adding items it can get really weird. I like your idea of automatically resetting the offsets when adding/removing items though, but that itself could end up as a big pain to users too, although should be more obvious what is going on to them...

One thing I am hoping to get added in before release is a theme option where I will just provide several different layout options someone can select from as a more "basic" option and the advanced user can have these more specific controls if needed, hoping that will ease the pain for users that don't want/need the full customization.

Would love to hear more thoughts on this from you and others.

**Comment by hiergiltdiestfu** [comment]
Well, the first possibility that comes to mind is that you keep the offsets, but anchor them to the actual edges of adjoining widgets. So the time area has invisible boundaries where the lower edge is also the upper edge for the area below, say the date area. So now the offset for the date area is not based on some fixed position in the root document (didn't check if this is how you do it, but it feels like it), but on the (variable) edge of the adjoining area. When the area moves or resizes, all transitively depending areas also move, but can never clip into areas where they did not clip into before, because the position is still relative to the moved edge. This does not work out when truly adding or removing elements, because the visible geometry of the added/removed areas might be different. This could be worked around by resetting the offsets of adjoining areas whenever an edge-relation changes.

All of this sounds like this needs a true layout manager component which ensures constraints or rules like this. A layout manager could also work by pushing areas away from edges until no clipping is found anymore. This is how network graphs are usually decluttered, but it's a computation-intensive thing that you probably don't want.

An alternative is to never truly add or remove areas, but always keep them in the scene, and just hide or unhide them, while keeping their geometry in place. That way, seemingly unrelated areas can never jump when an area is removed or added (like is the case with the date area when removing/adding the brackets). If you go this way, you can place all areas manually at compile-time, and the Offsets can be used to customize your placement. If the user changes the Offsets to make an area clip into another, that's his or her problem, not a layout bug.

**Comment by bluecaret** [comment]
Thank you for the options. There is a lot going on here including the offsets, and size of elements plus items like the brackets which are tied to the clocks but someone might want to visually make them look like they are wrapping the time and date which is why I have offsets to start with. And if I understand your first option correctly, that is esset what I am doing, there are invisible borders of such it's just the offset let's you go beyond that.

Here is an idea I have though, please let me know what you think...

To start I'm going to change the default display to be more standard with no offsets set so that users being more basic with their settings shouldn't see any clipping.

Second, if the user does set an offset and they toggle a new option I can open a dialog that informs them the new item could get clipped and they might need to adjust the offsets.

My only issue with this is if I do end up having "themes" to pick from with pre-set layouts and the user chooses those, they most likely will end up with clipping once they customize further. But that's where I hope the dialog message will be enough.

**Comment by bluecaret** [comment]
So for now I just simply changed this so that the default settings do not have any offsets applied meaning that if a user adds or removes anything no clipping should occur unless they themselves changed an offset. I think this will do for now, maybe someday I can explore a more complex layout feature but as it is this extension is already getting bigger than I had ever planned originally. You can check this out in the new Beta 3 update that I just released today. Thanks!
