### ISSUE TITLE
White screen on loading with black theme

### ISSUE THREAD

**Issue by TheoLecoq** [bluecaret/carettab#134]
Please is it possible to set the default background color to black? Cause with the black theme, when I open a new tab the white background appears first. and in the dark it's not really cool to be flashed like that

**Comment by bluecaret** [comment]
Unfortunately I do not know of a way to do that. It is a matter of how the browser loads a new page. Since it is the background color that displays before the extension has a chance to load at all, it is out of my control. I have compared with other "new tab" page extensions and have seen the same issue with those as well. If you know of one that does not do this let me know and I can investigate further.

I'd suggest you submit a bug report to Google Chrome asking them for when dark mode is enabled, change the default background that shows before a page is loaded.
