### ISSUE TITLE
some complaint about the new version

### ISSUE THREAD

**Issue by Alice-and-Bob** [bluecaret/carettab#161]
I cant believe that after i updated carettab and restarted it, I lost ALL MY OLD SETTINGS!!! Why not add a function to save or remember users' old settings? I have been using carettab for 2 years and this software has memorized many of my usage habits. This update now causes me to struggle to remember my previous common sites and Settings...

**Comment by bluecaret** [comment]
I am sorry for the frustration that it has caused. This was more than a simple update, I completely rebuilt the extension from the ground up using a new framework. Because of this and to make future updates easier, the way items are saved are very different from how they were. I also took way too long getting this update out in the first place. I didn't want to both bloat the code and the release time trying to incorporate a complex method to transfer settings over for this single time.

As far as the quick links go, I did add a transfer option for that. After the update you should have been presented with a message that explained settings won't carry over but quick links can be moved. There was then an option that let you copy those settings over, but it was only available right after the upgrade.

During the update I tried to ensure that future updates will be easier and without the need to drop settings like that again. Hopefully I will not have to do this ever again and settings will be able to remain from here on. I can assure you that I will try my best to avoid wiping settings in the future.

**Comment by Alice-and-Bob** [comment]
Well, I'm just following the update boot.Maybe it's a translation problem, as a Chinese user I don't seem to see the option to use the old Settings, maybe you should put this prompt at the beginning of the update? BTW, I like these new features, which allow me to customize my start page more.And after going through my history, I finally recovered most of my fast connections.Sorry for the emotional complaint.

**Comment by bluecaret** [comment]
I completely understand. The notice was at the very start after update, though it may not have been translated for you at that moment so maybe that was the issue. I'm happy to hear you are enjoying the update otherwise though. Thank you very much for your support!
