### ISSUE TITLE
Bug: Week number is off by one

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#183]
The week number does not display correctly. Currently on January 22nd it is showing as week 4 instead of 3.

Edit: Turns out it is set correctly, but Moment.js bases the week number off of locale (as in language set). To resolve this, should add an option to base Week number off the ISO Week Number.

**Comment by ChristophSchmidt1203** [comment]
Ya, I noticed this too. I think some calendar software offer options of what constitutes the first week of the year (i.e. how many days of the new year need to be in the first week to count as week number 1 rather than the last week of the last year.) - this could be an alternative, or maybe just look into what ISO says about it, like OP proposed.

(FWIW I had to disable week numbers because it's clashing with what Outlook and my paper calendar are telling me.)

**Comment by bluecaret** [comment]
An ISO option has been added in version 3.2.0, you should hopefully see this update on your machine within a week, as soon as Chrome and Edge approve it. Thank you.
