### ISSUE TITLE
Custom Font Not Loading (Firefox)

### ISSUE THREAD

**Issue by FrostedHedgehog** [bluecaret/carettab#185]
Downloaded a custom font and installed it to Windows 10. Typed it in the custom font field exactly as Windows 10 has named the font in its database.

The specific font in question is Press Start but I have tried other fonts as well; the main note here is the all the fonts I tried have a pixelated design, which the latest update removed; as far as I am aware as I can't find it.

Thank you for the amazing Addon!

**Comment by bluecaret** [comment]
I apologize for the very long reply! I did some testing and your correct, there is some weird things going on. I have tried many other fonts as well, all work fine except for "Press Start 2P" as downloaded from Google Fonts. I think this is something to do with the font itself rather than an issue with CaretTab. I will continue looking into this though, and I may just add Press Start back on as a font to choose from as before. I originally pulled it as it can cause issues with alignment of text given how wide the characters are, but given this issue I can look into adding it back as an alternative.

**Comment by bluecaret** [comment]
Hello @FrostedHedgehog, so after testing earlier I have restarted my computer and I am noticing the Press Start 2P is working for me. No idea why, but give it another try. Install your font, restart your computer and set the font name and see if that works. Below is a screenshot of my settings. Let me know if you continue having problems here.

![image](https://user-images.githubusercontent.com/9217636/114276314-f22eb680-99da-11eb-9c09-ccbadd03f260.png)
