### ISSUE TITLE
Provide instructions for carrying over settings

### ISSUE THREAD

**Issue by fiscalia8** [bluecaret/carettab#213]
My main computer's Firefox lost the customization settings during last update (back to default) and I'd love to be able to just copy the settings from my secondary computer, which for some mysterious reason updated just fine and all my pretty quicklinks and formatting are right there! 

In your changelog, you indicate "requires storage permissions" for sync support. After being unable to find that permission in the Firefox Extension options menu, I've dug into about:config with no luck. I also confirmed that most relevant items in about:config are identical between my two browsers (and if they weren't, I corrected it, but with no luck). So I think it might not be a Firefox issue.

~~The late May update had a handy feature which "detected" previous settings for CaretTab and allowed me to import, but that's not an option this time around.~~ (Edit to strikethrough; found this port was just for quicklinks, it's still working.) Please help me find the sync file and port it over!

**Comment by bluecaret** [comment]
Hello, sorry for the trouble your having. Firefox has been a bit of a pain with syncing in general.

My first question is, are you signed into Firefox on both machines? It should be syncing settings between the two, unless each are not on the same version of the extension right now? I just released 2 separate updates this week. The latest version is 3.4.1, I'd first make sure you get both to that version and see what happens. If you're still having problems then we can try a manual approach.

I do plan on getting an import/export feature added, at this point probably sooner rather than later. But for now we can get this manually for you. In Firefox on your machine that still has your settings you will need to follow these steps:

- Open the new tab page and press "ctrl+shift+k" to open the console window.
- At the bottom of the console window it gives you a place to type, in there type or paste in: 
`chrome.storage.sync.get(null, d => console.log(d))`
- That should spit out all your settings into a new line that will look something like this: 
![image](https://user-images.githubusercontent.com/9217636/120815796-04256500-c505-11eb-96bc-c51e9cc4cc32.png)
- Right-click on the word "object" and select "copy object"
- Open Notepad or any document and paste this into it, save it as a .txt if you can. 
- Please email that to me at bluecaret@outlook.com and I can get it formatted and ready to import to the other machine for you. You can also just paste that object here if you don't care about your settings being public.
- Please also check what version of the extension you are running on both machines. You can do this by going to `about:addons` in the URL, then click on CaretTab, near the bottom it should tell you the version number.
