### ISSUE TITLE
New tab page is stuck

### ISSUE THREAD

**Issue by ubless607** [bluecaret/carettab#227]
![image](https://user-images.githubusercontent.com/5417257/130568864-e06c8840-7d91-4c55-ad22-76a3d304ae49.png)

The clock and the weather sign is not working.
Reloading the tab returns blank page. Uninstalling and reinstalling the addon didn't help.

Version Info: 3.5.0
Firefox Version: 91.0.1 (64 bit)

**Comment by bluecaret** [comment]
I'm sorry for the trouble. Can you open the console and take a screen shot of that once you open a new window? Open the console by right-clicking the screen, select "inspect" and then select the "console" tab. 

Also can you please clarify the issue? So when you open firefox and get a new tab, things show fine but then you restart and things a blank? You showed a screenshot with the clock and weather showing, is that what it looks like when it is working or are you missing a background as well?

Thank you.

**Comment by bluecaret** [comment]
There was a bug with the new weather widget in the latest update. The issue was due to the source I get the weather data from, that source has fixed the issue now. Next time you load the new tab page try refreshing and it should work now. If you are still having issues then this is probably something else, and if so, please create a new issue here on GitHub. 

Thank you all for using CaretTab and for the bug reports!
