### ISSUE TITLE
Weather Widget: Forecast shows today instead of tomorrow

### ISSUE THREAD

**Issue by APalmer91** [bluecaret/carettab#236]
With the weather widget, the forecast option starts with today instead of tomorrow, resulting in a duplicate when you also have current weather turned on. I suppose that could be intentional, but if so, it would be nice to have the option either way.

**Comment by bluecaret** [comment]
This is intentional, as the "current" weather truly is current, where as "today" in the forecast is what it will be on average for the day. For example, you might wake up in the morning and it will show it is cold on the current, but on the forecast it shows it will be warm for the day so you can properly prepare for the day.

That being said, maybe I can add an option that will skip the current day within the forecast.

**Comment by bluecaret** [comment]
My pleasure!
