### ISSUE TITLE
most visited   layer under "message" and "search"

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#254]
![image](https://user-images.githubusercontent.com/388085/140933560-09a10bb6-a553-42b0-a8a0-edc92de0ea0e.png)

As  you can see in my config, I've enabled "most" visited. (1)

When I open the most visited popup (2)

The box   is under the search menu (3)

so 
* (minor) it's not  very  funny to read
* (major)  items aren't clickable.

currently spotted on 
* Firefox 91.3.0esr 
* Chrome 94.0.4606.71 
* Edge 95.0.1020.44

**Comment by bluecaret** [comment]
Thank you for the report!

**Comment by bluecaret** [comment]
Looking into this today, this is a bigger problem than I thought it would be due to how CSS works and how I structured the app. Unfortunately I won't be able to promise a quick fix on this one (and yes I'm aware it's been a year since this was reported 😞). I think this is going to take a major rebuild of how the widgets display in the app. Something I've been wanting to do anyway as it will improve a lot of customization, but it is going to have to wait till I have more time. Thank you very much for your patience with this issue!

**Comment by bluecaret** [comment]
Well I was wrong, I managed to get this working after all. It should be in the next update, releasing hopefully within a week.

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store. Keep a look out for it within a couple days.
