### ISSUE TITLE
Firefox Extension Outdated

### ISSUE THREAD

**Issue by BlazingFire007** [bluecaret/carettab#286]
I love this extension for Chrome/Chromium browsers, but I recently switched to Firefox and was disappointed to see it is very outdated compared to the chromium version.

My chrome has version 3.6.2 yet Firefox, when freshly installed, is only 2.3.1.

**Comment by bluecaret** [comment]
My apologies. I've pulled CaretTab from Firefox. I could not justify continued development there with the amount of users I had. Maybe in the future I can reconsider, but right now I just don't have the time. To answer your original question though, Firefox pulled the latest version due to an issue they found with it that did not have the time to fix.

I hope you continue using CaretTab on Chromium browsers.

**Comment by bluecaret** [comment]
@Rex501st thank you, I did notice that recently and removed it from the site. If you refresh it shouldn't be listed anymore.

**Comment by bluecaret** [comment]
Ahh man! I removed the button, completely forgot about the text there. Thank you so much for letting me know!
