### ISSUE TITLE
How to install the master  version ?

### ISSUE THREAD

**Issue by Moosh-be** [bluecaret/carettab#301]
Last released Version 3.6.2 have more than one year ( 17 Oct 2021)

master contain a lot of interresting patches.

How to build and install the master version ?

**Comment by bluecaret** [comment]
I just released a minor change on Oct 16th, 2022, a couple weeks ago (ironically, exactly a year since the last one). You should be seeing version 3.6.3 in your browser already, or you might need to manually update? The update was only released on Chrome though so if you are on Edge, the update will come, but when I make the next update. I'm working on 3.6.4 as we speak, it will mostly be a bunch of bug fixes, hoping to get it out within a week, give or take, assuming life doesn't get in the way. Thanks!

**Comment by Moosh-be** [comment]
Great.
Indeed I have chrome, edge and ff installed, but edge is  my most used.

Thank you 4 all

**Comment by bluecaret** [comment]
Version 3.6.4 has been published to the Chrome Web Store and Edge store. Keep a look out for it within a couple days. (Edge usually takes longer).
