### ISSUE TITLE
CaretTab won't open in startpage

### ISSUE THREAD

**Issue by HenkeDaniil** [bluecaret/carettab#71]

**Comment by bluecaret** [comment]
Hello, by startpage do you mean the first page that opens when you start Firefox? If so I don't believe I have control over that, I can only replace "new tabs", and as far as I'm aware Firefox does not allow replacing that startpage.

If this is not what you mean, can you please provide more details as to what the issue is and what your system is? 

Thank you.

**Comment by ptolemarch** [comment]
I'm sorry to comment on a closed issue, but I have a workaround: It seems possible to set CaretTab, explicitly, as your home page in Firefox.

- First, type "caret" in your location bar. This will create a dropdown, and CaretTab should be one of the choices. The URL listed should be something like `moz-extension://89e8679b-210c-4a26-b133-50eb5a404457/carettab.htm`.
- Set this URL as your Home Page in preferences, and set new windows to display your home page.
