### ISSUE TITLE
URL chrome://apps/ Not Working

### ISSUE THREAD

**Issue by asadi5** [bluecaret/carettab#87]
![chrome apps launcher](https://user-images.githubusercontent.com/40297741/41851958-acdb5b44-7857-11e8-80fb-d1616e029196.PNG)
Is there a way to add "chrome://apps/" to links, and have it open like any other links. Currently, you can add it to the "Links" in "Settings". However, once the selected label appears on the page, clicking on it does not do anything. If you right click on that label, and do a "Copy link address", and then paste it in the address bar, and hit enter, it opens the Chrome Apps page. Thanks.

**Comment by bluecaret** [comment]
Hello, yes this is a limitation Chrome seems to have. The solution here is for me to add an option that you can toggle for this link. I am adding this to the next version update. Thanks!

**Comment by plastikhub** [comment]
Hey, thanks for this. Has this been pushed yet? Instead of opening another issue, I figured I would post here. I'd like to load a chrome extension "chrome-extension://..." via custom link, but currently it only loads a blank page. Surely with extensions available like New Tab Redirect, etc. that have that ability built in, this functionality can be implemented here too right?

**Comment by drozel** [comment]
chrome-extension://<extension link> also not working...

**Comment by bluecaret** [comment]
Hi, so I will have options that will allow you to toggle on/off links for chrome apps, bookmarks manager, history and chrome tab, this is still planned for the next update. Right now I don't have plans for adding a custom chrome:// link though due to complexity that would be needed in the UI for a niche feature. If you would like to create a new issue for custom chrome links, I can take a look at it for a future update.

**Comment by bluecaret** [comment]
This has been completed in CaretTab v3 which is currently in Beta at the moment, so I'll be closing this as fixed. If you would like to check it out, you can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
